name: Continuous Integration

on:
  push:
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest
    env:
      MONGODB_USER: ${{ secrets.MONGODB_USER }}
      MONGODB_PASS: ${{ secrets.MONGODB_PASS }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      MONGODB_DATABASE: ${{ secrets.MONGODB_DATABASE }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      PORT: ${{ secrets.PORT }}
    steps:
    - uses: actions/checkout@v2
    - name: Build back-end
      run: |
        cd back-end
        docker build -t back-end .
    - name: Test back-end
      run: |
        cd back-end
        npm install
        npm test

  frontend:
    runs-on: ubuntu-latest
    env:
      REACT_APP_BACKEND_HOST: ${{ secrets.REACT_APP_BACKEND_HOST }}
    steps:
    - uses: actions/checkout@v2
    - name: Build front-end
      run: |
        cd front-end
        docker build -t front-end .
